<?php

 // module/Album/view/album/album/index.phtml:

 $title = 'My Team';
 $this->headTitle($title);
 ?>
 <div class="about-page-wrapper">
        <div class="top-contents">
                <h1>- Our Mission -</h1>
                <p>To provide the most actionable app store data.</p>
        </div>
        
        <div class="top-middle-contents"  style="margin: 0 auto;
    max-width: 65%;">
                <h1>About</h1>
                <p>At Apptopia, we all come to work every day because we want to solve the biggest problem in mobile. Everyone is guessing. Publishers dont know what apps to build, how to monetize them, or even what to price them at. Advertisers and brands dont know where their target users are, how to reach them, or even how much they need to spend in order to do so. Investors arent sure which apps and genres are growing the quickest, and where users are really spending their time (and money).

Throughout the history of business, people use data to make more informed decisions. Our mission at Apptopia is to make the app economy more transparent. Today we provide the most actionable mobile app data and  insights in the industry. We want to make this data available to as many people as possible (not just the top 5%).</p>
        </div>
        
 <h1 style="text-align: center;"><?php echo $this->escapeHtml($title); ?></h1>
 
 <div class="my-team-section">
 <?php foreach ($abouts as $album) : ?>
    <div class="single-member">
     <h1><?php echo $this->escapeHtml($album->name);?></h1>
     <p><?php   echo $this->escapeHtml($album->email);?></p>
     <p><?php  echo $this->escapeHtml($album->phone);?></p>
     <p><?php  echo $this->escapeHtml($album->address);?></p>
     
</div>
 <?php endforeach; ?>

 </div>
 </div>